# Generated by Django 5.2.8 on 2025-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_paystack_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
