# Generated by Django 5.2.8 on 2025-11-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Account'), ('ussd', 'USSD'), ('qr', 'QR Payment'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
    ]
