# Generated by Django 5.2.8 on 2025-11-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
