# Generated by Django 5.2.8 on 2025-11-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Account'), ('ussd', 'USSD'), ('qr', 'QR Payment'), ('bank_transfer', 'Bank Transfer')], default='card', max_length=20),
        ),
    ]
