"""
Django settings for snedaEcommerceAPI project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*!@9oayqjy43r1r6ga$h05z6w_7u1pxlyq5pyr&uxzkcdgc&+i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
# Add testserver for test environments
ALLOWED_HOSTS += ['testserver']

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'drf_yasg',
    'users',
    'products',
    'carts',
    'orders',
    'payments',
    'shipping',
    'reviews',
    'notifications',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

# Custom user model
AUTH_USER_MODEL = "users.CustomUser"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'snedaEcommerceAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snedaEcommerceAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

# email backend
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST FRAMEWORK SHITS
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES" : (
        "users.authentication.CookieJWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",  
}
# JWT SETTINGS
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# CORS: frontend must be allowed to send cookies
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000' ).split(',')
CORS_ALLOW_CREDENTIALS = True

# CSRF / cookie-related (tweak for prod)
CSRF_COOKIE_HTTPONLY = False # we need JS to read csrftoken cookie (so False)
CSRF_COOKIE_SAMESITE = "Lax" # or "Strict" or "None" (with Secure)
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true' # set True in production (HTTPS)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}

# for logging
# Create a "logs" directory inside your project root if it doesn't exist

'''
LOG_DIR = Path(BASE_DIR, "logs")
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    # Allow Django’s default loggers to still work
    "disable_existing_loggers": False,

    # -----------------------------
    #  FORMATTERS
    #  How logs will look
    # -----------------------------
    "formatters": {
        # Detailed log output (recommended for saving to files)
        "verbose": {
            "format": "[{asctime}] [{levelname}] {name} - {message}",
            "style": "{",
        },
        # Short logs (used for console)
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },

    # -----------------------------
    #  HANDLERS
    #  Where logs are written to
    # -----------------------------
    "handlers": {
        # Log only ERROR & above to errors.log (server crashes, unhandled exceptions)
        "file_error": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "errors.log"),
            "maxBytes": 1024 * 1024 * 5,  # Limit log file to 5MB
            "backupCount": 5,  # Keep 5 backup log files
            "formatter": "verbose",
            "level": "ERROR",
        },

        # Log WARNING & above to warnings.log (throttling, validation issues, etc.)
        "file_warning": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "warnings.log"),
            "maxBytes": 1024 * 1024 * 3,  # 3MB max size
            "backupCount": 3,
            "formatter": "verbose",
            "level": "WARNING",
        },

        # Logs to the terminal console (for debugging during development)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },

    # -----------------------------
    #  LOGGERS
    #  Which parts of Django/DRF generate logs
    # -----------------------------
    "loggers": {
        # Django general logs (warnings, errors, anything internal)
        "django": {
            "handlers": ["file_error", "file_warning"],  # Save warnings & errors to files
            "propagate": True,  # Allow logs to bubble up
        },

        # Logs for 500 errors coming from views, middleware, etc.
        "django.request": {
            "handlers": ["file_error"],  # Only log errors
            "level": "ERROR",
            "propagate": False,
        },

        # DRF-specific logs (throttling, parsing issues, schema warnings)
        "rest_framework": {
            "handlers": ["file_warning"],  # Only warnings
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# to watch live logs
# run this in a separate terminal: tail -f logs/errors.log
'''