"""
Django settings for snedaEcommerceAPI project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*!@9oayqjy43r1r6ga$h05z6w_7u1pxlyq5pyr&uxzkcdgc&+i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()]
# testserver for test environments
ALLOWED_HOSTS += ['testserver']

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'drf_yasg',
    'users',
    'products',
    'carts',
    'orders',
    'payments',
    'shipping',
    'reviews',
    'notifications',
    'corsheaders',
    'admin_panel',
    'background_tasks',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]
# ── Celery configuration ──────────────────────────────────────────────────────
# Uses the same Redis instance already configured for caching (logical db 0)

from celery.schedules import crontab

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_IGNORE_RESULT = False # make sure results are stored in the bacckend
CELERY_TIMEZONE = 'UTC'
# Retry failed tasks up to 3 times with a 60-second delay (set per task)
CELERY_TASK_ACKS_LATE = True          # only ack after the task completes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 # one task per worker at a time (safer for payment work)
# celery beat schedule
CELERY_BEAT_SCHEDULE = {
    'expire-reservations-every-15-minutes': {
        'task': 'products.tasks.expire_reservations',
        'schedule': crontab(minute='*/15'),
    },
    'cancel-unpaid-orders-every-30-minutes': {
        'task': 'orders.tasks.cancel_unpaid_orders',
        'schedule': crontab(minute='*/30'),
    },
}
# Custom user model
AUTH_USER_MODEL = "users.CustomUser"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'snedaEcommerceAPI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snedaEcommerceAPI.wsgi.application'


# Database
# https://docs.djangoproje15ct.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

# Cache Config (Redis)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",                                     
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),  # uses redis logical db
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# ── Email / SMTP configuration (Gmail) ───────────────────────────────────────
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "willadan667@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")   # App Password from .env
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", f"Sneda Ecommerce <{EMAIL_HOST_USER}>")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST FRAMEWORK SETTINGS
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES" : (
        "users.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler", 
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '2000/day',
        'user': '10000/day',
        'sensitive': '5/minute'
    }
}

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS & SSL Settings (Only for HTTPS/Production)
if os.environ.get('DJANGO_DEBUG', 'False').lower() == 'false':
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_HTTPONLY is False as per existing requirement for SPA to read token

# JWT SETTINGS
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# CORS: frontend must be allowed to send cookies
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',') if origin.strip()]
CORS_ALLOW_CREDENTIALS = True # allow cookies to be sent

# CSRF / cookie-related (tweak for prod)
CSRF_COOKIE_HTTPONLY = False # we need JS to read csrftoken cookie (so False)
CSRF_COOKIE_SAMESITE = "Lax" # or "Strict" or "None" (with Secure)
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true' # set True in production (HTTPS)
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() == 'true'

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT access token (header: Authorization: Bearer <token>)'
        },
        'Cookie': {
            'type': 'apiKey',
            'name': 'sessionid',
            'in': 'cookie',
            'description': 'Django session cookie for authenticated requests'
        }
    },
    'SECURITY_REQUIREMENTS': [
        {'Bearer': []},
        {'Cookie': []}
    ],
    'USE_SESSION_AUTH': True,
    'PERSIST_AUTH': True,
    'VALIDATOR_URL': '',
}

# for logging
# Create a "logs" directory inside your project root if it doesn't exist


LOG_DIR = Path(BASE_DIR, "logs")
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    # Allow Django’s default loggers to still work
    "disable_existing_loggers": False,

    # -----------------------------
    #  FORMATTERS
    #  How logs will look
    # -----------------------------
    "formatters": {
        # Detailed log output (recommended for saving to files)
        "verbose": {
            "format": "[{asctime}] [{levelname}] {name} - {message}",
            "style": "{",
        },
        # Short logs (used for console)
        "simple": {
            "format": "{levelname}: {message}",
            "style": "{",
        },
    },

    # -----------------------------
    #  HANDLERS
    #  Where logs are written to
    # -----------------------------
    "handlers": {
        # Log only ERROR & above to errors.log (server crashes, unhandled exceptions)
        "file_error": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "errors.log"),
            "maxBytes": 1024 * 1024 * 5,  # Limit log file to 5MB
            "backupCount": 5,  # Keep 5 backup log files
            "formatter": "verbose",
            "level": "ERROR",
        },

        # Log WARNING & above to warnings.log (throttling, validation issues, etc.)
        "file_warning": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "warnings.log"),
            "maxBytes": 1024 * 1024 * 3,  # 3MB max size
            "backupCount": 3,
            "formatter": "verbose",
            "level": "WARNING",
        },

        # Logs to the terminal console (for debugging during development)
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },

    # -----------------------------
    #  LOGGERS
    #  Which parts of Django/DRF generate logs
    # -----------------------------
    "loggers": {
        # Django general logs (warnings, errors, anything internal)
        "django": {
            "handlers": ["file_error", "file_warning"],  # Save warnings & errors to files
            "propagate": True,  # Allow logs to bubble up
        },

        # Logs for 500 errors coming from views, middleware, etc.
        "django.request": {
            "handlers": ["file_error"],  # Only log errors
            "level": "ERROR",
            "propagate": False,
        },

        # DRF-specific logs (throttling, parsing issues, schema warnings)
        "rest_framework": {
            "handlers": ["file_warning"],  # Only warnings
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# to watch live logs
# run this in a separate terminal: tail -f logs/errors.log for linux
# run Get-Content logs\errors.log -Wait -Tail 10 for windows powershell
