# Generated by Django 5.2.6 on 2025-10-15 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_otp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('hire_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(unique=True)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('on_patrol', 'On Patrol'), ('responding', 'Responding'), ('off_duty', 'Off Duty')], default='off_duty', max_length=20)),
                ('last_location_update', models.DateTimeField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
