# Generated by Django 5.2.6 on 2025-10-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_client_manager_securitypersonnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypersonnel',
            name='badge_number',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='securitypersonnel',
            name='emergency_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='securitypersonnel',
            name='last_location_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='securitypersonnel',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
