# Generated by Django 5.2.8 on 2025-11-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_securitypersonnel_badge_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitypersonnel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='securitypersonnel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SecurityPersonnel',
        ),
    ]
