# Generated by Django 5.2.8 on 2026-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_checkoutattempt_address_and_more'),
        ('orders', '0012_alter_order_approved_alter_order_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkoutattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address__isnull', False), ('pickup_location__isnull', True)), models.Q(('address__isnull', True), ('pickup_location__isnull', False)), _connector='OR'), name='exactly_one_fulfillment_target'),
        ),
    ]
