# Generated by Django 5.2.8 on 2026-03-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviews_product_reviews_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-date_created']},
        ),
    ]
