# Generated by Django 5.2.8 on 2026-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
