# Generated by Django 5.2.8 on 2026-03-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_pickup_order_pickup_location_and_more'),
        ('shipping', '0003_shipping_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='orders.order'),
        ),
    ]
