# Generated by Django 5.2.8 on 2026-03-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='related_object_id',
            field=models.BigIntegerField(),
        ),
    ]
