# Generated by Django 5.2.8 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
