# Generated by Django 5.2.8 on 2026-03-16 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 16, 15, 59, 23, 837263, tzinfo=datetime.timezone.utc)),
        ),
    ]
