# Generated by Django 5.2.8 on 2026-03-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_id_alter_reservation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
