# Generated by Django 5.2.8 on 2026-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_is_pickup_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('NIA', 'National Information Agency'), ('SPINTEX', 'Spintex'), ('OSU', 'Osu')], max_length=255, null=True),
        ),
    ]
