# Generated by Django 5.2.8 on 2026-03-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('cancellation_pending', 'Cancellation Pending')], default='pending', max_length=20),
        ),
    ]
