# Generated by Django 5.2.8 on 2026-03-31 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def update_order_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    PickupFulfillment = apps.get_model('orders', 'PickupFulfillment')
    
    # Try to get Shipping model if it exists at this point
    Shipping = None
    try:
        Shipping = apps.get_model('shipping', 'Shipping')
    except (LookupError, ValueError):
        pass

    # 1. Update status mapping
    # 'fulfilled' and 'delivered' are legacy and should map to 'paid'
    Order.objects.filter(status__in=['fulfilled', 'delivered']).update(status='paid')

    # 2. Migrate fulfillment data
    for order in Order.objects.all():
        # Check if fulfillment already exists (idempotency check)
        has_pickup = PickupFulfillment.objects.filter(order=order).exists()
        has_shipping = (Shipping and Shipping.objects.filter(order=order).exists())

        if order.is_pickup and not has_pickup:
            # Transfer pickup_location to PickupFulfillment
            loc = getattr(order, 'pickup_location', None)
            if loc:
                PickupFulfillment.objects.create(
                    order=order,
                    location=loc,
                    status='pending'  # Default for existing orders
                )
        elif not order.is_pickup and not has_shipping and Shipping:
            # Transfer shipping_address to Shipping
            addr = getattr(order, 'shipping_address', None)
            if addr:
                Shipping.objects.create(
                    order=order,
                    address=addr,
                    status='pending'
                )

def reverse_order_statuses(apps, schema_editor):
    # This is a no-op as the legacy fields will be recreated but data is lost in downgrade
    # unless we explicitly reversed it, but usually not required for this type of refactor.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_marked_for_review_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('NIA', 'National Information Agency'), ('SPINTEX', 'Spintex'), ('OSU', 'Osu')], max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_pickup_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_fulfillment', to='orders.order')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(update_order_statuses, reverse_code=reverse_order_statuses),
        migrations.RemoveField(
            model_name='order',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]

