# Generated by Django 5.2.8 on 2026-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_backfill_legacy_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('cancellation_pending', 'Cancellation Pending')], default='pending', max_length=20),
        ),
    ]
