# Generated by Django 5.2.8 on 2026-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productimage_image_productimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
